# FROM node:22-alpine
FROM oven/bun:latest

ARG API_URL="app"
ARG SERVER_API_URL="app"
ENV SERVER_API_URL=$SERVER_API_URL
ENV API_URL=$API_URL

WORKDIR /app/front/
COPY ./src/client .

RUN bun install --force


CMD bun run docker:dev 